name: Deploy hello-world-app

on:
  push:
    branches: [ hello-world-app ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
     
      - name: Run cppcheck
        uses: deep5050/cppcheck-action@main
        
      - name: Publish results
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'hello-world-app'
          
      - name: Install googleTest
        uses: MarkusJx/googletest-installer@v1.1
        
      - name: Install cmake
        uses: Symbitic/install-cmake@v0.1.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: True
              
      - name: Run cmake
        run:  cmake Hello-world
        
      - name: Cmake build
        run: cmake --build .
