name: Deploy hello-world-app

on:
  push:
    branches: [ hello-world-app ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
     
      - name: Run cppcheck
        uses: deep5050/cppcheck-action@main
        
      - name: Publish results
        uses: mikeal/publish-to-github-action@master
        
      - name: Install cmake
        uses: Symbitic/install-cmake@v0.1.0
      
      - run: cd Hello-world
      
      - name: Make build dir
        run: mkdir build && cd build
              
      - name: Run cmake
        run: cmake ..
        
      - name: Cmake build
        run: cmake --build .
